version: '3'

services:
  server:
    image: server
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/QasrHIS"
      JWT_SECRET: "our-secret"
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"


  postgres:
    image: postgres:16.0
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: QasrHIS
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: