version: "3"

services:
  server:
    image: server
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432/Qasr"
      JWT_SECRET: "our-secret"
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"

  postgres:
    image: postgres:16.0
    container_name: database
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Qasr
    volumes:
      - postgres-data:/var/lib/postgresql/data

  next_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: next_app
    ports:
      - "3000:3000"
    environment:
      BASE_URL: "http://localhost:3000"
      NEXT_PUBLIC_API_URL: "http://localhost:4000"

  model:
    image: model
    container_name: model
    build:
      dockerfile: Dockerfile
      context: ./ocr-server
    ports:
      - "5000:5000"

volumes:
  postgres-data:
