const Endpoints = {
  base: "https://qasr-server-lqj1.onrender.com/api",
  // base: "http://localhost:4000/api",

  user: {
    login: "/user/login",
    me: "/user/me",
  },
  employee: {
    list: "/employee",
    details: "/employee/:id",
    create: "/employee",
    update: "/employee/:id",
    delete: "/employee/:id",
  },
  visit: {
    list: "/visit",
    details: "/visit/:visitcode",
    transfer: "/visit/:visitcode/status",
    create: "/visit",
    createAnonymously:
      "/visit/anonymous",
    update: "/patient",
    complaint:"visit/complaint/:visitCode",
    triageAX:
      "visit/triageAx",
    streaming: "/streaming/event",

  },
  incident: {
    create: "/incident",
    list: "/incident",
    details: "/incident/:id",
  },

  lookups: {
    list: "/enums",
  },
  department: {
    list: "/department",
    details: "/department/:id",
    create: "/department",
    update: "/department/:id",
    delete: "/department/:id",
  },
  person: {
    details: "/person/:ssn",
  },
  room: {
    list: "/room",
    details: "/room/:id",
    create: "/room",
    update: "/room/:id",
    delete: "/room/:id",
  },
  specialization: {
    list: "/specialization",
    details: "/specialization/:id",
    create: "/specialization",
    update: "/specialization/:id",
    delete: "/specialization/:id",
  },
  subdepartment: {
    list: "/subdepartment",
    details: "/subdepartment/:id",
    create: "/subdepartment",
    update: "/subdepartment/:id",
    updateAssignFeatures:
      "/subdepartment/:id/assignfeatures",
    delete: "/subdepartment/:id",
  },
  feature: {
    list: "/feature",
    details: "/feature/:id",
    create: "/feature",
    update: "/feature/:id",
    delete: "/feature/:id",
  },
  permission: {
    list: "/permission",
    details: "/permission/:id",
    create: "/permission",
    update: "/permission/:id",
    delete: "/permission/:id",
  },
  role: {
    list: "/role",
    details: "/role/:id",
    create: "/role",
    update: "/role/:id",
    delete: "/role/:id",
  },
  allergy: {
    list: "/allergy",
    details: "/allergy/:id",
    create: "/allergy",
    update: "/allergy/:id",
    delete: "/allergy/:id",
  },
  primarySurvey: {
    list: "/primarySurvey",
    details: "/primarySurvey/:id",
    create: "/primarySurvey",
    update: "/primarySurvey/:id",
    delete: "/primarySurvey/:id",
  },
  surgery: {
    list: "/surgery",
    details: "/surgery/:id",
    create: "/surgery",
    update: "/surgery/:id",
    delete: "/surgery/:id",
  },
  medicalProblem: {
    list: "/medicalProblem",
    details: "/medicalProblem/:id",
    create: "/medicalProblem",
    update: "/medicalProblem/:id",
    delete: "/medicalProblem/:id",
  },
  medication: {
    list: "/medication",
    details: "/medication/:id",
    create: "/medication",
    update: "/medication/:id",
    delete: "/medication/:id",
  },
  prescription: {
    list: "/prescription",
    details: "/prescription/:id",
    create: "/prescription",
    update: "/prescription/:id",
    delete: "/prescription/:id",
  },
  diagnosis: {
    list: "/diagnosis",
    details: "/diagnosis/:id",
    create: "/diagnosis",
    update: "/diagnosis/:id",
    delete: "/diagnosis/:id",
  },
  vitals: {
    list: "/vitals",
    details: "/vitals/:id",
    create: "/vitals",
    update: "/vitals/:id",
    delete: "/vitals/:id",
  },
  triage: {
    list: "/triageAx",
    details: "/triageAx/:id",
    create: "/triageAx",
    update: "/triageAx/:id",
    delete: "/triageAx/:id",
  },
  labs: {
    list: "/lab-test",
    details: "/lab-test/:id",
    create: "/lab-test",
    update: "/lab-test/:id",
    delete: "/lab-test/:id",
  },
  radiologies: {
    list: "/radiology-image",
    details: "/radiology-image/:id",
    create: "/radiology-image",
    update: "/radiology-image/:id",
    delete: "/radiology-image/:id",
  },
};
export default Endpoints;
