import AccessibleIcon from "@mui/icons-material/Accessible";
import AccessibilityIcon from "@mui/icons-material/Accessibility";
import DescriptionIcon from "@mui/icons-material/Description";
import { HeaderItem } from "@/core/shared/components/CustomDataTable";
export interface DataItem {
  id: string;
  name: string;
  email: string;
  phone: string;
  address: string;
  description: string;
  icon?: React.ReactNode;
}

export const data: DataItem[] = [
  {
    id: "1",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
    icon: <AccessibilityIcon onClick={() => console.log("icon clicked")} />,
  },
  {
    id: "2",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
    icon: <AccessibleIcon />,
  },
  {
    id: "3",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
    icon: <AccessibilityIcon />,
  },
  {
    id: "4",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
    icon: <AccessibleIcon />,
  },
  {
    id: "5",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "6",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
    icon: <AccessibilityIcon />,
  },
  {
    id: "7",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
    icon: <AccessibilityIcon />,
  },
  {
    id: "8",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
    icon: <AccessibleIcon />,
  },
  {
    id: "9",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "10",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
    icon: <AccessibleIcon />,
  },
  {
    id: "11",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "12",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
    icon: <AccessibleIcon />,
  },
  {
    id: "13",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "14",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "15",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "16",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "17",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "18",
    name: "Leanne Graham Leanne Graham Leanne Graham Leanne Graham",
    email: "user1@healu.com user1@healu.com user1@healu.com user1@healu.com",
    phone:
      "1-770-736-8031x564421-770-736-8031 x564421-770-736-8031 x564421-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "19",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "20",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
  {
    id: "21",
    name: "Leanne Graham",
    email: "user1@healu.com",
    phone: "1-770-736-8031 x56442",
    address: "Kulas Light",
    description: "description",
  },
];

export const header: HeaderItem[] = [
  {
    id: "id",
    label: "ID",
    minWidth: 50,
    maxWidth: 50,
    tableCellProps: { align: "center" },
    sortable: true,
    filterable: true,
    searchable: true,
    onClick: () => {},
  },
  {
    id: "name",
    label: "Name",
    minWidth: 100,
    maxWidth: 100,
    tableCellProps: { align: "center" },
    sortable: true,
    filterable: true,
    searchable: true,
    onClick: () => {},
  },
  {
    id: "email",
    label: "Email",
    minWidth: 100,
    maxWidth: 100,
    tableCellProps: { align: "center" },
    sortable: true,
    filterable: true,
    searchable: true,
    onClick: () => {},
  },
  {
    id: "phone",
    label: "Phone",
    minWidth: 100,
    maxWidth: 100,
    tableCellProps: { align: "center" },
    sortable: true,
    filterable: true,
    searchable: true,
    onClick: () => {},
  },
  {
    id: "address",
    label: "Address",
    minWidth: 100,
    maxWidth: 100,
    tableCellProps: { align: "center" },
    sortable: true,
    filterable: true,
    searchable: true,
    onClick: () => {},
  },
  {
    id: "description",
    label: "Description",
    minWidth: 100,
    maxWidth: 100,
    tableCellProps: { align: "center" },
    sortable: true,
    filterable: true,
    searchable: true,
    onClick: () => {},
    component: <DescriptionIcon />,
  },
  {
    id: "status",
    label: "Status",
    minWidth: 100,
    maxWidth: 100,
    tableCellProps: { align: "center" },
    sortable: false,
    filterable: false,
    searchable: false,
    onClick: () => {},
    isIcon: true,
  },
];
