name: Backend Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# jobs:
#   test:
#     name: Run Tests
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:latest
#         env:
#           POSTGRES_DB: QasrHIS
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     strategy:
#       matrix:
#         node-version: [18]

# jobs:
#   test:
#     name: Run Backend Checks
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Install dependencies
#         run: npm install
#         working-directory: ./server/

#       - name: Run Linter
#         run: npm run lint
#         working-directory: ./server/

#       - name: Type Check
#         run: npm run type-check
#         working-directory: ./server/

#       - name: Build Project
#         run: npm run build
#         working-directory: ./server/
