export enum IdentityEnum {
    NATIONALIDCARD,
    PASSPORT
}

export enum GenderEnum {
    MALE,
    FEMALE
}

export enum RoleEnum {
    ADMIN,
    EMPLOYEE,
    DOCTOR,
    NURSE
}

export enum ShiftEnum {
    MORNING8,
    AFTERNOON8,
    NIGHT8,
    MORNING12,
    NIGHT12,
    LONG
}

export enum GovernateEnum {
    ALEXANDRIA,
    ASWAN,
    ASYUT,
    LUXOR,
    RED_SEA,
    BEHEIRA,
    BENI_SUEF,
    PORT_SAID,
    SOUTH_SINAI,
    GIZA,
    DAKAHLIA,
    DAMIETTA,
    SOHAG,
    SUEZ,
    SHARQIA,
    NORTH_SINAI,
    GHARBIA,
    FAYOUM,
    CAIRO,
    QALYUBIA,
    QENA,
    KAFR_EL_SHEIKH,
    MATRUH,
    MONUFIA,
    MINYA
}

export enum DepartmentEnum {
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    GENERAL_SURGERY,
    GYNECOLOGY,
    NEUROLOGY,
    NEUROSURGERY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    OTORHINOLARYNGOLOGY,
    PEDIATRICS,
    PSYCHIATRY,
    UROLOGY,
    RADIOLOGY,
    ANESTHESIOLOGY,
    EMERGENCY,
    INTERNAL_MEDICINE,
    PATHOLOGY,
    PHYSICAL_MEDICINE,
    PLASTIC_SURGERY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    THORACIC_SURGERY,
    VASCULAR_SURGERY,
    DENTISTRY,
    NURSING,
    PHARMACY,
    PHYSIOTHERAPY,
    ADMINISTRATION,
    OTHER
}